# Generated by Django 2.2 on 2021-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='official',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='official',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
