# Generated by Django 2.2 on 2021-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0002_auto_20210607_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='indice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='official',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
